---
- name: Install and configure Grafana
  hosts: grafana
  become: true  # This assumes you have privilege escalation configured

  tasks:
    - name: Configure Grafana YUM repository
      copy:
        dest: /etc/yum.repos.d/grafana.repo
        content: |
          [grafana]
          name=grafana
          baseurl=https://packages.grafana.com/oss/rpm
          repo_gpgcheck=1
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.grafana.com/gpg.key
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt

    - name: Install Grafana package
      yum:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: true

